version: "3.8"

networks:
  bookstore-network:
    external: true

services:
  catalog-service:
    image: sivaprasadreddy/bookstore-catalog-service
    container_name: catalog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://catalog-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SWAGGER_API_GATEWAY_URL: http://api-gateway:8989/catalog
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8081:8081"
    restart: unless-stopped
    mem_limit: 700m
    labels:
      logging: "promtail"
    networks:
      - bookstore-network

  order-service:
    image: sivaprasadreddy/bookstore-order-service
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ORDERS_CATALOG_SERVICE_URL: http://api-gateway:8989/catalog
      DB_URL: jdbc:postgresql://orders-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: bookstore-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      OAUTH2_SERVER_URL: http://keycloak:9191
      SWAGGER_API_GATEWAY_URL: http://api-gateway:8989/orders
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8082:8082"
    restart: unless-stopped
    mem_limit: 700m
    labels:
      logging: "promtail"
    networks:
      - bookstore-network

  notification-service:
    image: sivaprasadreddy/bookstore-notification-service
    container_name: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://notifications-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: bookstore-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8083:8083"
    restart: unless-stopped
    mem_limit: 700m
    labels:
      logging: "promtail"
    networks:
      - bookstore-network

  api-gateway:
    image: sivaprasadreddy/bookstore-api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CATALOG_SERVICE_URL: http://catalog-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8989:8989"
    restart: unless-stopped
    mem_limit: 700m
    labels:
      logging: "promtail"
    networks:
      - bookstore-network

  bookstore-webapp:
    image: sivaprasadreddy/bookstore-webapp
    container_name: bookstore-webapp
    environment:
      SPRING_PROFILES_ACTIVE: docker
      BOOKSTORE_API_GATEWAY_URL: http://api-gateway:8989
      OAUTH2_SERVER_URL: http://keycloak:9191
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8080:8080"
    restart: unless-stopped
    mem_limit: 700m
    labels:
      logging: "promtail"
    # networks:
    #   - bookstore-network
